### ISSUE TITLE
insertIf does not show field on initial render

### ISSUE THREAD

**Issue by alexandermeyer** [mighty-justice/fields-ant#67]
I have a modal that uses `FormModal` with a `cardConfig` that uses `insertIf` for a field. This `insertIf` works great if the values in the modal are changed. On initial render, however, the model that is passed to the `insertIf` function is empty, even though fields have defaults.

**Comment by rkuykendall** [comment]
I think this could be solved by moving initialValue logic into FormManager so that we can generate the initial model before the form is mounted.
