### ISSUE TITLE
ObjectSearchCreate not nullifying createFields

### ISSUE THREAD

**Issue by rkuykendall** [mighty-justice/fields-ant#98]

**Comment by ronaldzuniga** [comment]
Can you post a video or steps to reproduce and expected values to understand what's exactly the issue?

**Comment by rkuykendall** [comment]
@ronaldzuniga I'll write a failing test now. Though technically I think there's already lots of tests in the codebase that aren't failing but should be.

**Comment by rkuykendall** [comment]
@ronaldzuniga Added failing test to https://github.com/mighty-justice/fields-ant/pull/134/files
